#!/usr/bin/python3

import os
import base64
import json
import sys
import random

if len(sys.argv) != 3:
    print("Usage ./gen <executable> <path>")
    exit(1)

mouli_files = {}

for subdir, dirs, files in os.walk("%s/source" % sys.argv[2]):
    for file in files:
        file = os.path.join(subdir, file)
        if os.path.isfile(file):
            with open(file, "rb") as f:
                data = f.read()
            file = file.replace("%s/source/" % sys.argv[2], "")
            mouli_files[file] = base64.b64encode(data).decode("utf-8")

mouli_files_data = base64.b64encode(json.dumps(mouli_files).encode()).decode("utf-8")

codes = []
while len(codes) < 10:
    new_code = "%04d" % random.randint(0, 9999)
    if new_code not in codes:
        codes.append(new_code)
ultimate_code = "%06d" % random.randint(0, 999999)

with open("data/.script", "r") as script:
    script_data = script.read()

script_data = script_data.format(codes=json.dumps(codes), ultimate=ultimate_code, base64=mouli_files_data, exec=sys.argv[1])
script_data_b64 = base64.b64encode(script_data.encode()).decode("utf-8")

mouli_script = "#!/usr/bin/python3\ncode = \"{script}\"\nimport base64\ncode = base64.b64decode(code).decode()\ncode_obj = compile(code, \"mouli\", \"exec\")\nexec(code_obj)".format(script=script_data_b64)
with open("data/.installer", "r") as installer:
    installer_data = installer.read()
    installer_script = installer_data.format(content=base64.b64encode(mouli_script.encode()).decode())

with open("%s/installer" % sys.argv[2], "w+") as installer:
    installer.write(installer_script)

os.chmod("%s/installer" % sys.argv[2], 0o755)

with open("%s/codes.txt" % sys.argv[2], "w+") as codes_file:
    codes_file.write("Codes:\n"+"\n".join(codes)+"\n\nUltimate code:\n"+ultimate_code)

print("\033[92mGenerated successfully\033[0m")