name: Parser

on:
  push:
    branches:
      - main
      - master

jobs:
  parse_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xzf geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - uses: actions/checkout@v2
      - name : "Install Python dependencies"
        run : pip install Markdown reportlab selenium weasyprint PyPDF2

      - name: "Parse markdown subjects"
        run: |
          for file in $(ls -d */ | sed 's#/##')
          do
              if [ ! -d "$file/subject" ]; then
                  echo "::error file=$file,title="No subject folder"::$file"
                  continue
              fi
              if [ ! -f "$file/subject/data.txt" ]; then
                  echo "::error file=$file/subject,title="No subject data.txt"::$file/subject"
                  continue
              fi
              data=$(cat $file/subject/data.txt)
              stable=$(echo "$data" | cut -d$'\n' -f3)
              if [ "$stable" = "stable" ]; then
                  echo "::notice file=$file/subject/data.txt,title="Marked as stable"::$file/subject/data.txt"
                  continue
              fi
              title=$(echo "$data" | cut -d$'\n' -f1)
              if [ -z "$title" ]; then
                  echo "::error file=$file/subject/data.txt,title="No title"::$file/subject/data.txt"
                  continue
              fi
              version=$(echo "$data" | cut -d$'\n' -f2)
              if [ -z "$version" ]; then
                  echo "::error file=$file/subject/data.txt,title="No version"::$file/subject/data.txt"
                  continue
              fi
              md=$(ls $file/subject/*.md | head -n1)
              if [ -z "$md" ]; then
                  echo "::error file=$file/subject,title="No markdown file"::$file/subject"
                  continue
              fi
              cd .github/workflows/parser && python3 cc_subjects.py "../../../$md" "$title" "$version" && cd ../../..
          done
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions