name: Parser

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - main

jobs:
  parse_directories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name : "Install Python dependencies"
        run : pip install -r .github/workflows/parser/requirements.txt
      - name: "Parse markdown subjects"
        run: |
          set -e
          cd .github/workflows/parser
          subjects=$(ls -d ../../../*/)
          for directory in ${subjects}
          do
              if [ ! -d "$directory/subject" ]; then
                  echo "::error directory=$directory,title="No subject folder"::$directory"
                  continue
              fi
              md=$(find "$directory/subject" "$directory/Subject" -name "*.md" -type f 2>/dev/null | head -n1)
              if [ ! -f "$md" ]; then
                  echo "::error directory=$directory/subject,title="No markdown found"::$directory/subject"
                  continue
              fi
              # This will write the pdf in $directory. Meaning in the parent directory of the markdown file.
              python3 cc_subjects.py "$md"
              if [ $? -ne 0 ]; then
                  echo "::error directory=$directory/subject,title="Conversion failed"::$directory/subject"
              fi
          done
      - uses: EndBug/add-and-commit@v9
        with:
          add: "-- . ':!.github'"
          default_author: github_actions
